### ISSUE TITLE
on android, after select animation viewer ;

### ISSUE THREAD

**Issue by halukmy** [fabionuno/LottieXamarin-Samples#1]
View view = inflater.Inflate(Resource.Layout.fragment_animation, container, false);

==>

Unhandled Exception:

Android.Views.InflateException: Binary XML file line #1: Error inflating class TextView

**Comment by fabionuno** [comment]
Hi @halukmy  I have update the sample app with Lottie Android 2.0.0 beta1
Can you check if the issue still occurs to you?

**Comment by halukmy** [comment]
im on my way

**Comment by fabionuno** [comment]
@halukmy I think the problem is related with the use of vector drawables on pre-lollipop

**Comment by halukmy** [comment]
@fabionuno i was testted it on 4.2 and 4.4 

but i will try new release asap

**Comment by halukmy** [comment]
perfect problem just handled

thanks for great support for xamarin.android

xamarin.forms for sucks :))
